name: Changelog Generator

on:  
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Determine whether or not to commit changelog to repo on selected branch.'
        required: true
        default: "false"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with: 
          fetch-depth: 0
      - run: docker run -v $PWD:/workdir quay.io/git-chglog/git-chglog:0.15.1 --next-tag $(node --eval="process.stdout.write(require('./package.json').version)") --output CHANGELOG.md  
      - name: GitHub Upload Release Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: CHANGELOG.md
          path: |
            ./CHANGELOG.md
      # publish it
      - name: Publish content
        if: ${{ github.event.inputs.publish == 'true' }}      
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./CHANGELOG.md
          git commit -m 'docs(changelog): update changelog'
          git push origin ${GITHUB_REF##*/}