name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@4756e6330fe1e0a736690d3cfd9f11c9399c2ed4 # v0.4.1
        with:
          project-url: https://github.com/orgs/open-amt-cloud-toolkit/projects/5
          github-token: ${{ secrets.PROJECTS_PAT }}
