name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    name: Validate PR and Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/commitlint.config.js
