name: "Semantic Pull Request"

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  main:
    name: Validate PR and Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@0d749a1a91d4770e983a7b8f83d4a3f0e7e0874e # v5.4.4
        with:
          configFile: .github/commitlint.config.js
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional@17.4.2
      - uses: JulienKode/pull-request-name-linter-action@8c05fb989d9f156ce61e33754f9802c9d3cffa58 # v0.5.0
        with:
          configuration-path: ./.github/commitlint.config.js
